import { Component, EventEmitter, Input, Output, Renderer2, ElementRef, HostListener, OnInit, Directive } from '@angular/core';

@Component({
  selector: 'app-index-user',
  templateUrl: './index-user.component.html',
  styleUrls: ['./index-user.component.scss']
})
export class IndexUserComponent{
  @Input() id!: string;
  @Input() maxSize!: number;
  @Output() pageChange!: EventEmitter<number>;
  @Output() pageBoundsCorrection!: EventEmitter<number>;
  submenuRemixe: boolean = false;
  submenuGeneros: boolean = false;
  submenuBuscador: boolean = false;
  itemForPage: number = 20;
  numberPage: number = 1;

  constructor(private elementRef: ElementRef) { }
  isElementVisible = false;
  screenResolution?: string;

  listaSong = [] = [
    { 
      id:1,
      image:"../../../assets/index-usuario/caratularecomendadosytop10.png",
      autor:"Bad Bunny",
      nombre:"Un preview",
      subtitulo:"Intro Outro",
      genero:"Reggaeton",
      puntaje:"958 PM",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg",
    },
    { 
      id:2,
      image:"../../../assets/index-usuario/caratularecomendadosytop10.png",
      autor:"Bad Bunny",
      nombre:"Un preview",
      subtitulo:"Intro Outro",
      genero:"Reggaeton",
      puntaje:"958 PM",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    { 
      id:3,
      image:"../../../assets/index-usuario/caratularecomendadosytop10.png",
      autor:"Bad Bunny",
      nombre:"Un preview",
      subtitulo:"Intro Outro",
      genero:"Reggaeton",
      puntaje:"958 PM",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    { 
      id:4,
      image:"../../../assets/index-usuario/caratularecomendadosytop10.png",
      autor:"Bad Bunny",
      nombre:"Un preview",
      subtitulo:"Intro Outro",
      genero:"Reggaeton",
      puntaje:"958 PM",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    { 
      id:5,
      image:"../../../assets/index-usuario/caratularecomendadosytop10.png",
      autor:"Bad Bunny",
      nombre:"Un preview",
      subtitulo:"Intro Outro",
      genero:"Reggaeton",
      puntaje:"958 PM",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    { 
      id:6,
      image:"../../../assets/index-usuario/caratularecomendadosytop10.png",
      autor:"Bad Bunny",
      nombre:"Un preview",
      subtitulo:"Intro Outro",
      genero:"Reggaeton",
      puntaje:"958 PM",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    { 
      id:7,
      image:"../../../assets/index-usuario/caratularecomendadosytop10.png",
      autor:"Bad Bunny",
      nombre:"Un preview",
      subtitulo:"Intro Outro",
      genero:"Reggaeton",
      puntaje:"958 PM",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    { 
      id:8,
      image:"../../../assets/index-usuario/caratularecomendadosytop10.png",
      autor:"Bad Bunny",
      nombre:"Un preview",
      subtitulo:"Intro Outro",
      genero:"Reggaeton",
      puntaje:"958 PM",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    { 
      id:9,
      image:"../../../assets/index-usuario/caratularecomendadosytop10.png",
      autor:"Bad Bunny",
      nombre:"Un preview",
      subtitulo:"Intro Outro",
      genero:"Reggaeton",
      puntaje:"958 PM",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    { 
      id:10,
      image:"../../../assets/index-usuario/caratularecomendadosytop10.png",
      autor:"Bad Bunny",
      nombre:"Un preview",
      subtitulo:"Intro Outro",
      genero:"Reggaeton",
      puntaje:"958 PM",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    }
  ]
  songsList = [] = [
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    },
    {
      fecha: "10/03/2023",
      remixerLogo: "../../../assets/index-usuario/caratulatabla.png",
      artista: "Alok, The Chainsmokers Y Mae Stephens",
      tema: "One In A Millon",
      version: "Intro Outro",
      bpm: "121",
      genero:"Latin Pop",
      descarga: "../../../assets/index-usuario/image-song.png",
      iconStart: "../../../assets/index-usuario/start.svg",
      iconDownload: "../../../assets/index-usuario/download.svg",
      iconLove: "../../../assets/index-usuario/love.svg"
    }
  ]

  totalPageList = Math.round(this.songsList.length / this.itemForPage)
}